// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdobSIQUvKA-b9MtWN3gL02P88QlQdFAw',
    appId: '1:755064093212:web:0df4d83620faee47f03dd9',
    messagingSenderId: '755064093212',
    projectId: 'test3-a13bd',
    authDomain: 'test3-a13bd.firebaseapp.com',
    storageBucket: 'test3-a13bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvA_TZ3nvln91uJCVg9-hIy2S96Q1ZaP8',
    appId: '1:755064093212:android:d1c815b4bd9569aaf03dd9',
    messagingSenderId: '755064093212',
    projectId: 'test3-a13bd',
    storageBucket: 'test3-a13bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArzU2z0XqZPpqvhCjE9ue3IatAqMpkZ8',
    appId: '1:755064093212:ios:7dd33ee7c2f5c7bef03dd9',
    messagingSenderId: '755064093212',
    projectId: 'test3-a13bd',
    storageBucket: 'test3-a13bd.firebasestorage.app',
    iosBundleId: 'com.example.test3',
  );

}